spring:
  profiles:
    active: local
  main:
    banner-mode: "OFF"
  application:
    name: demo-app

logging:
  level.root: DEBUG
  file:
    name: /var/log/${spring.application.name}/applog.log
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(PLOP){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(PLOP){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api/rest
  undertow:
    accesslog:
      enabled: true
      dir: /var/log/${spring.application.name}/
      prefix: accesslog.
      pattern: "%v %a %l %u %t \"%r\" %s %B %D"

management:
  endpoint:
    restart:
      enabled: true

